config/routes.rb
Rails.application.routes.draw do
  get 'purchases', to: 'purchases#index'
  post 'purchases/upload'
  get 'invoices/', to: 'invoices#index'
  post 'invoices/upload', to: 'invoices#upload'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/merchant.rb
class Merchant < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :purchaser
  belongs_to :item
  belongs_to :merchant

  delegate :name, to: :purchaser, prefix: true
  delegate :name, to: :merchant, prefix: true
  delegate :address, to: :merchant, prefix: true
  delegate :description, to: :item, prefix: true
  delegate :price, to: :item, prefix: true

  def total
	  amount.to_i * item.price.to_f
  end
end

app/models/purchaser.rb
class Purchaser < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @purchases = Purchase.all
  end

  def upload
    if attachment = params[:attachment]
      purchases = purchase_service.upload(attachment)
    else
      flash[:alert] = 'There\'s no file.'
    end
    redirect_to action: :index
  end

  private

  def purchase_service
    @purchase_service ||= PurchaseService.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NuuvemWebTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/purchases/index.html.erb
<h1 class="text-center">Purchases</h1>
<div class="card">
  <div class="card-header">
    <%= form_tag(purchases_upload_path, {multipart: true}) do %>
      <%= file_field_tag 'attachment' %>
      <%= button_tag "Enviar" %>
    <% end %>
  </div>
  <div class="card-body">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Purchaser Name</th>
          <th>Merchant address</th>
          <th>Merchant Name</th>
          <th>Item Description</th>
          <th>Item Price</th>
          <th>Purchase Count</th>
          <th>Purchase Total</th>
        </tr>
      </thead>
      <tbody>
        <% @purchases.each do |purchase| %>
          <tr>
            <td><%= purchase.purchaser_name %></td>
            <td><%= purchase.merchant_name%></td>
            <td><%= purchase.merchant_address%></td>
            <td><%= purchase.item_description%></td>
            <td><%= number_to_currency(purchase.item_price, unit: 'R$ ', separator: ",", delimiter: ".")%></td>
            <td><%= purchase.amount%></td>
            <td><%= number_to_currency(purchase.total, unit: 'R$ ', separator: ",", delimiter: ".")%></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="6"><strong></strong>Total</td>
          <td><%= number_to_currency(@purchases.map(&:total).reduce(&:+), unit: 'R$ ', separator: ",", delimiter: ".") %></td>
        </tr>
      </tfoot>
    </table>
  </div>
  </dov>

app/views/purchases/upload.html.erb
<h1>Purchase#upload</h1>
<p>Find me in app/views/purchase/upload.html.erb</p>